spring:
  zipkin:
    base-url: http://localhost:8085/

server:
  port: 8082

eureka:
  instance:
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    order-service:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      stripPrefix: false
    payment-service:
      path: /payment/**
      serviceId: payment-service
      stripPrefix: false

