spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/order_service?useSSL=false&characterEncoding=UTF-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:8085/

  application:
    name: order-service
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}

server:
  port: 8083
eureka:
  instance:
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000